version: "3.8"

services:
  docusaurus:
    image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docusaurus
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start"]